-- =============================================================================
-- SCRIPT MAESTRO DE RESET Y DESPLIEGUE - ENTREGABLE FINAL (VERSIÓN TOTAL)
-- Proyecto: Clubes de Lectura (MEA)
-- =============================================================================

SET AUTOCOMMIT OFF;
SET FEEDBACK ON;
SET DEFINE OFF;
SET SERVEROUTPUT ON;

PROMPT >>> ELIMINANDO VISTAS...
DROP VIEW MEA_v_detalle_lectores;
DROP VIEW MEA_v_clubes_instituciones;
DROP VIEW MEA_v_socios_activos;
DROP VIEW MEA_v_catalogo_libros;
DROP VIEW MEA_v_historial_pago_socios;
DROP VIEW MEA_v_agenda_reuniones;
DROP VIEW MEA_v_contactos_sistema;
DROP VIEW MEA_v_idiomas_hablados;
DROP VIEW MEA_v_libros_favoritos;
DROP VIEW MEA_v_reporte_inasistencias;
DROP VIEW MEA_v_produccion_obras;
DROP VIEW MEA_v_elencos_y_premiados;
DROP VIEW MEA_v_trayectoria_grupos;
DROP VIEW MEA_v_clubes_asociados;

PROMPT >>> ELIMINANDO PROCEDIMIENTOS...
DROP PROCEDURE MEA_dividir_grupo;
DROP PROCEDURE MEA_inscribir_miembro;
DROP PROCEDURE MEA_generar_calendario;
DROP PROCEDURE MEA_realizar_reunion;
DROP PROCEDURE MEA_cerrar_calendario;
DROP PROCEDURE MEA_retirar_miembro;
DROP PROCEDURE MEA_asignar_favoritos;
DROP PROCEDURE MEA_crear_club;

PROMPT >>> ELIMINANDO FUNCIONES...
DROP FUNCTION MEA_conversion_monetaria;
DROP FUNCTION MEA_promedio_part_mensual_tipo;
DROP FUNCTION MEA_edad_miembro;
DROP FUNCTION MEA_antiguedad_miembro;
DROP FUNCTION MEA_participacion_bimestre_miembro;
DROP FUNCTION MEA_antiguedad_en_club_miembro;

PROMPT >>> ELIMINANDO TABLAS (ORDEN INVERSO DE DEPENDENCIAS)...
DROP TABLE MEA_FAVORITOS CASCADE CONSTRAINTS;
DROP TABLE MEA_INASISTENTES CASCADE CONSTRAINTS;
DROP TABLE MEA_REFERENCIAS CASCADE CONSTRAINTS;
DROP TABLE MEA_A_L CASCADE CONSTRAINTS;
DROP TABLE MEA_REUNIONES_CALENDARIO CASCADE CONSTRAINTS;
DROP TABLE MEA_LIBROS CASCADE CONSTRAINTS;
DROP TABLE MEA_ASOCIACIONES CASCADE CONSTRAINTS;
DROP TABLE MEA_HISTORICO_GRUPOS CASCADE CONSTRAINTS;
DROP TABLE MEA_MEJORES_ACTORES CASCADE CONSTRAINTS;
DROP TABLE MEA_ELENCOS CASCADE CONSTRAINTS;
DROP TABLE MEA_GRUPOS CASCADE CONSTRAINTS;
DROP TABLE MEA_PRESENTACIONES CASCADE CONSTRAINTS;
DROP TABLE MEA_PAGOS_MEMBRESIAS CASCADE CONSTRAINTS;
DROP TABLE MEA_SOCIOS CASCADE CONSTRAINTS;
DROP TABLE MEA_OBRAS CASCADE CONSTRAINTS;
DROP TABLE MEA_TELEFONOS CASCADE CONSTRAINTS;
DROP TABLE MEA_HABLAN CASCADE CONSTRAINTS;
DROP TABLE MEA_REPRESENTANTES CASCADE CONSTRAINTS;
DROP TABLE MEA_LECTORES CASCADE CONSTRAINTS;
DROP TABLE MEA_CLUBES CASCADE CONSTRAINTS;
DROP TABLE MEA_CIUDADES CASCADE CONSTRAINTS;
DROP TABLE MEA_AUTORES CASCADE CONSTRAINTS;
DROP TABLE MEA_PAISES CASCADE CONSTRAINTS;
DROP TABLE MEA_IDIOMAS CASCADE CONSTRAINTS;
DROP TABLE MEA_INSTITUCIONES CASCADE CONSTRAINTS;

PROMPT >>> ELIMINANDO SECUENCIAS...
DROP SEQUENCE MEA_seq_instituciones;
DROP SEQUENCE MEA_seq_idiomas;
DROP SEQUENCE MEA_seq_paises;
DROP SEQUENCE MEA_seq_autores;
DROP SEQUENCE MEA_seq_ciudades;
DROP SEQUENCE MEA_seq_clubes;
DROP SEQUENCE MEA_seq_lectores;
DROP SEQUENCE MEA_seq_representantes;
DROP SEQUENCE MEA_seq_hablan;
DROP SEQUENCE MEA_seq_obras;
DROP SEQUENCE MEA_seq_pagos_membresias;
DROP SEQUENCE MEA_seq_grupos;
DROP SEQUENCE MEA_seq_id_orden;
DROP SEQUENCE MEA_seq_favoritos;
DROP TYPE MEA_conversion_table;
DROP TYPE MEA_conversion_row;

PROMPT >>> ELIMINADO TODO

COMMIT;

