-- =============================================================================
-- SCRIPT MAESTRO DE RESET Y DESPLIEGUE - RÚBRICA 2.2
-- Proyecto: Clubes de Lectura (MEA)
-- =============================================================================

SET AUTOCOMMIT OFF;
SET FEEDBACK ON;
SET DEFINE OFF;
SET SERVEROUTPUT ON;

PROMPT >>> ELIMINANDO TABLAS (ORDEN INVERSO DE DEPENDENCIAS)...
DROP TABLE MEA_FAVORITOS CASCADE CONSTRAINTS;
DROP TABLE MEA_INASISTENTES CASCADE CONSTRAINTS;
DROP TABLE MEA_REFERENCIAS CASCADE CONSTRAINTS;
DROP TABLE MEA_A_L CASCADE CONSTRAINTS;
DROP TABLE MEA_REUNIONES_CALENDARIO CASCADE CONSTRAINTS;
DROP TABLE MEA_LIBROS CASCADE CONSTRAINTS;
DROP TABLE MEA_ASOCIACIONES CASCADE CONSTRAINTS;
DROP TABLE MEA_HISTORICO_GRUPOS CASCADE CONSTRAINTS;
DROP TABLE MEA_MEJORES_ACTORES CASCADE CONSTRAINTS;
DROP TABLE MEA_ELENCOS CASCADE CONSTRAINTS;
DROP TABLE MEA_GRUPOS CASCADE CONSTRAINTS;
DROP TABLE MEA_PRESENTACIONES CASCADE CONSTRAINTS;
DROP TABLE MEA_PAGOS_MEMBRESIAS CASCADE CONSTRAINTS;
DROP TABLE MEA_SOCIOS CASCADE CONSTRAINTS;
DROP TABLE MEA_OBRAS CASCADE CONSTRAINTS;
DROP TABLE MEA_TELEFONOS CASCADE CONSTRAINTS;
DROP TABLE MEA_HABLAN CASCADE CONSTRAINTS;
DROP TABLE MEA_REPRESENTANTES CASCADE CONSTRAINTS;
DROP TABLE MEA_LECTORES CASCADE CONSTRAINTS;
DROP TABLE MEA_CLUBES CASCADE CONSTRAINTS;
DROP TABLE MEA_CIUDADES CASCADE CONSTRAINTS;
DROP TABLE MEA_AUTORES CASCADE CONSTRAINTS;
DROP TABLE MEA_PAISES CASCADE CONSTRAINTS;
DROP TABLE MEA_IDIOMAS CASCADE CONSTRAINTS;
DROP TABLE MEA_INSTITUCIONES CASCADE CONSTRAINTS;

PROMPT >>> ELIMINANDO SECUENCIAS...
DROP SEQUENCE MEA_seq_instituciones;
DROP SEQUENCE MEA_seq_idiomas;
DROP SEQUENCE MEA_seq_paises;
DROP SEQUENCE MEA_seq_autores;
DROP SEQUENCE MEA_seq_ciudades;
DROP SEQUENCE MEA_seq_clubes;
DROP SEQUENCE MEA_seq_lectores;
DROP SEQUENCE MEA_seq_representantes;
DROP SEQUENCE MEA_seq_hablan;
DROP SEQUENCE MEA_seq_obras;
DROP SEQUENCE MEA_seq_pagos_membresias;
DROP SEQUENCE MEA_seq_grupos;
DROP SEQUENCE MEA_seq_id_orden;
DROP SEQUENCE MEA_seq_favoritos;

COMMIT;

PROMPT >>> 1. CREANDO ESTRUCTURA (creates.sql)...
@../rubrica2_1/creates.sql

PROMPT >>> 2. INSERTANDO DATOS MAESTROS (inserts.sql)...
@../rubrica2_1/inserts.sql

PROMPT >>> 3. COMPILANDO FUNCIONES...
@../rubrica2_1/functions.sql

PROMPT >>> 4. COMPILANDO PROCEDURES (procedures.sql)...
@procedures.sql

PROMPT >>> 5. COMPILANDO TRIGGERS (triggers.sql)...
@triggers.sql

PROMPT >>> 6. INSERTANDO DATOS DE PRUEBA (test_data.sql)...
@../rubrica2_1/test_data.sql

PROMPT >>> ¡RESET MAESTRO FINALIZADO CON ÉXITO!
